services:
  webapp:
    build: WebApp
    image: banquidle-webapp
    ports:
      - "3001:3000"
    environment:
      RAILS_ENV: production
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    networks:
      - cache
      - api
    depends_on:
      - redis
  
  redis:
    image: redis@sha256:0e9ce48d0db4865e805389edcb078996322e85c5216834d1f55c99b79e4aebc5
    volumes:
      - redis_data:/data
    networks:
      - cache

  bot:
    build: Bot
    restart: always
    networks:
      - api

volumes:
  redis_data:

networks:
  cache:
  api:
